### PR TITLE
Update Java prereq in README

### PR DESCRIPTION
**Pull request by arvindkrishnakumar-okta**

### CODE REVIEW

**Review by JayNewstrom — COMMENTED** [review]
Should we add an or JDK 11?

**Comment by arvindkrishnakumar-okta** [comment]
> Should we add an or JDK 11?

No, we have not tested this with JDK 11 yet.

**Comment by JayNewstrom** [comment]
I think we're testing with jdk 11 on every build: https://github.com/okta/okta-idx-java/blob/master/.travis.yml#L5

**Comment by arvindkrishnakumar-okta** [comment]
> I think we're testing with jdk 11 on every build: https://github.com/okta/okta-idx-java/blob/master/.travis.yml#L5

Ah sorry, yes.. let me add JDK 11 also.

**Comment by arvindkrishnakumar-okta** [comment]
> > I think we're testing with jdk 11 on every build: https://github.com/okta/okta-idx-java/blob/master/.travis.yml#L5
> 
> Ah sorry, yes.. let me add JDK 11 also.

done

**Review by JayNewstrom — APPROVED** [review]

**Pull request merged**
